# Machine-specific paths - generated by cmds\setup.ps1.  DO NOT commit.
$env:ANDROID_STUDIO_HOME = 'C:\Program Files\Android\Android Studio'
$env:JAVA_HOME           = 'C:\Program Files\Android\Android Studio\jbr'
$env:ANDROID_SDK_ROOT    = 'C:\Users\aaa\AppData\Local\Android\Sdk'
$env:ANDROID_HOME        = 'C:\Users\aaa\AppData\Local\Android\Sdk'
$env:GRADLE_USER_HOME    = 'C:\Users\aaa\.gradle'
$env:PUB_CACHE           = 'C:\Users\aaa\AppData\Local\Pub\Cache'
$env:PATH                = 'C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools;C:\Users\aaa\AppData\Local\Android\Sdk\cmdline-tools\latest\bin;' + $env:PATH
