# ─────────────────────────────────────────────────────────────────────────────
#  vLearn2 — First-time machine setup / path reset
#
#  Run once after `git pull` on a new machine, or any time you want to change
#  where the Android SDK, Gradle cache, or pub cache lives.
#
#  Steps performed:
#    1. Prompts for Android SDK, Gradle cache, and pub-cache paths
#    2. Saves answers to cmds\env-local.ps1  (gitignored, machine-specific)
#    3. Generates flutter_app\android\local.properties  (sdk.dir)
#    4. Seeds the vendored Gradle wrapper zip into the Gradle dists cache
#    5. Installs the offline Gradle init script
#
#  Re-run any time to reset paths.
# ─────────────────────────────────────────────────────────────────────────────
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ROOT             = Split-Path $PSScriptRoot -Parent
$ENV_LOCAL        = "$PSScriptRoot\env-local.ps1"
$GRADLE_VERSION   = '8.14'
$GRADLE_VARIANT   = 'all'
$GRADLE_ZIP_NAME  = "gradle-$GRADLE_VERSION-$GRADLE_VARIANT.zip"
$GRADLE_DIST_HASH = '6umpftuah39kegplpls29ixk'   # deterministic hash of the gradle-8.14-all URL
$VENDORED_ZIP     = "$ROOT\tools\gradle\$GRADLE_ZIP_NAME"

# ── helpers ───────────────────────────────────────────────────────────────────

function Ask-Path {
    param([string]$Label, [string]$Default)
    Write-Host "  $Label"
    Write-Host "  Current : $Default" -ForegroundColor DarkGray
    $ans = Read-Host "  New value (Enter to keep)"
    if ([string]::IsNullOrWhiteSpace($ans)) { return $Default }
    return $ans.Trim().TrimEnd('\')
}

# ── load existing env-local.ps1 so defaults reflect prior choices ─────────────
if (Test-Path $ENV_LOCAL) {
    Write-Host "Loading existing config from cmds\env-local.ps1 ..."
    . $ENV_LOCAL
}

# ── resolve defaults ──────────────────────────────────────────────────────────
$defaultSdk = if ($env:ANDROID_SDK_ROOT) { $env:ANDROID_SDK_ROOT } `
              elseif ($env:ANDROID_HOME)  { $env:ANDROID_HOME }     `
              else                        { 'C:\Android\Sdk' }

$defaultGradle = if ($env:GRADLE_USER_HOME) { $env:GRADLE_USER_HOME } `
                 else                        { "$env:USERPROFILE\.gradle" }

$defaultPub = if ($env:PUB_CACHE) { $env:PUB_CACHE } `
              else                 { "$env:LOCALAPPDATA\Pub\Cache" }

# ── interactive prompts ───────────────────────────────────────────────────────
Write-Host ''
Write-Host '=== vLearn2 machine setup ===' -ForegroundColor Cyan
Write-Host 'Press Enter to keep the current value, or type a new absolute path.'
Write-Host ''

$sdkDir     = Ask-Path 'Android SDK dir  (ANDROID_SDK_ROOT)' $defaultSdk
$gradleHome = Ask-Path 'Gradle cache dir (GRADLE_USER_HOME)' $defaultGradle
$pubCache   = Ask-Path 'Pub cache dir    (PUB_CACHE)'        $defaultPub

# ── confirm ───────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host 'Will configure:' -ForegroundColor Cyan
Write-Host "  ANDROID_SDK_ROOT = $sdkDir"
Write-Host "  GRADLE_USER_HOME = $gradleHome"
Write-Host "  PUB_CACHE        = $pubCache"
Write-Host ''
$ok = Read-Host 'Proceed? [Y/n]'
if ($ok -match '^[Nn]') { Write-Host 'Aborted.'; exit 0 }

# ── 1. Write cmds\env-local.ps1 ───────────────────────────────────────────────
Write-Host ''
Write-Host '--- Writing cmds\env-local.ps1 ---'
@"
# Machine-specific paths — generated by cmds\setup.ps1.  DO NOT commit.
`$env:ANDROID_SDK_ROOT = '$sdkDir'
`$env:ANDROID_HOME     = '$sdkDir'
`$env:GRADLE_USER_HOME = '$gradleHome'
`$env:PUB_CACHE        = '$pubCache'
"@ | Set-Content $ENV_LOCAL -Encoding UTF8
# Apply immediately in this session
$env:ANDROID_SDK_ROOT = $sdkDir
$env:ANDROID_HOME     = $sdkDir
$env:GRADLE_USER_HOME = $gradleHome
$env:PUB_CACHE        = $pubCache
Write-Host 'Written.'

# ── 2. Generate flutter_app\android\local.properties ─────────────────────────
Write-Host ''
Write-Host '--- Generating flutter_app\android\local.properties ---'
$localProps = "$ROOT\flutter_app\android\local.properties"
$sdkEscaped = $sdkDir -replace '\\', '\\'
"sdk.dir=$sdkEscaped" | Set-Content $localProps -Encoding UTF8
Write-Host "Written: $localProps"

# ── 3. Seed Gradle wrapper dists cache ───────────────────────────────────────
Write-Host ''
Write-Host '--- Seeding Gradle wrapper dists cache ---'
if (-not (Test-Path $VENDORED_ZIP)) {
    Write-Warning "Vendored zip not found: $VENDORED_ZIP"
    Write-Warning 'Run cmds\bootstrap_offline_gradle.bat first to download it, then re-run setup.'
} else {
    $distDir = "$gradleHome\wrapper\dists\gradle-$GRADLE_VERSION-$GRADLE_VARIANT\$GRADLE_DIST_HASH"
    $destZip = "$distDir\$GRADLE_ZIP_NAME"
    if (-not (Test-Path $destZip)) {
        New-Item -ItemType Directory -Force -Path $distDir | Out-Null
        Copy-Item $VENDORED_ZIP -Destination $destZip
        Write-Host "Seeded: $destZip"
    } else {
        Write-Host 'Already seeded — skipping.'
    }
}

# ── 4. Install offline Gradle init script ────────────────────────────────────
Write-Host ''
Write-Host '--- Installing offline Gradle init script ---'
$initSrc  = "$ROOT\tools\gradle\init.d\offline.init.gradle"
$initDest = "$gradleHome\init.d\offline.init.gradle"
if (Test-Path $initSrc) {
    New-Item -ItemType Directory -Force -Path (Split-Path $initDest) | Out-Null
    Copy-Item $initSrc -Destination $initDest -Force
    Write-Host "Installed: $initDest"
} else {
    Write-Warning "Init script not found: $initSrc — skipping."
}

# ── done ──────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '=== Setup complete ===' -ForegroundColor Green
Write-Host ''
Write-Host '  Paths are active in this shell session.'
Write-Host '  To reload them in a NEW shell, run:'
Write-Host "      . cmds\env-local.ps1" -ForegroundColor Yellow
Write-Host ''
Write-Host '  Build offline:  flutter build apk --debug'
Write-Host '  Go online:      cmds\vlearn2-online.ps1 on'
Write-Host '  Go offline:     cmds\vlearn2-online.ps1 off'
