import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;

import '../config/app_config.dart';
import '../datapack/datapack_installer.dart' show unpackedRootForGroup;
import '../datapack/datapack_paths.dart';

/// Per-file entry from manifest.json.
class ModelFile {
  const ModelFile({
    required this.relativePath,
    required this.sha256,
    required this.sizeBytes,
  });

  factory ModelFile.fromJson(Map<String, dynamic> j) => ModelFile(
        relativePath: j['path'] as String,
        sha256: j['sha256'] as String,
        sizeBytes: (j['size'] as num).toInt(),
      );

  final String relativePath;
  final String sha256;
  final int sizeBytes;
}

/// Top-level manifest structure. The shape is intentionally tiny so an admin
/// can hand-write it if needed.
class ModelManifest {
  const ModelManifest({
    required this.version,
    required this.sttModel,
    required this.ttsModel,
    required this.vadModel,
    required this.voices,
    required this.files,
    this.synthesized = false,
  });

  factory ModelManifest.fromJson(Map<String, dynamic> j) => ModelManifest(
        version: j['version'] as String,
        sttModel: j['stt']?['name'] as String? ?? 'unknown',
        ttsModel: j['tts']?['name'] as String? ?? 'unknown',
        vadModel: j['vad']?['name'] as String? ?? 'unknown',
        voices:
            ((j['tts']?['voices'] as List?) ?? const []).cast<String>(),
        files: ((j['files'] as List?) ?? const [])
            .cast<Map<String, dynamic>>()
            .map(ModelFile.fromJson)
            .toList(),
      );

  final String version;
  final String sttModel;
  final String ttsModel;
  final String vadModel;
  final List<String> voices;
  final List<ModelFile> files;

  /// True when this manifest was generated by scanning the disk (the
  /// `app_config.json` `stt` override path has the files but no
  /// manifest.json). Hash verification is skipped for synthesized
  /// manifests — admin placed the files manually, there's no signed
  /// digest to check against, presence + non-zero size is enough.
  final bool synthesized;
}

enum FileVerificationStatus { ok, missing, hashMismatch, sizeMismatch }

class FileVerification {
  const FileVerification({
    required this.file,
    required this.status,
    this.message,
  });
  final ModelFile file;
  final FileVerificationStatus status;
  final String? message;
}

enum ModelRegistryStatus { notReady, ready, corrupt, manifestMissing }

class ModelRegistrySnapshot {
  const ModelRegistrySnapshot({
    required this.status,
    required this.modelRoot,
    this.manifest,
    this.verifications = const [],
  });

  final ModelRegistryStatus status;
  final String modelRoot;
  final ModelManifest? manifest;
  final List<FileVerification> verifications;

  bool get isReady => status == ModelRegistryStatus.ready;
}

/// Owns the on-disk model bundle, the manifest, and verification.
class ModelRegistry {
  ModelRegistry({
    @visibleForTesting Directory? overrideRoot,
    String? modelOverridePath,
  })  : _overrideRoot = overrideRoot,
        _modelOverridePath = modelOverridePath;

  final Directory? _overrideRoot;

  /// Optional sdcard path from `app_config.json` `model` field. When
  /// set AND it contains a recognisable on-device speech layout
  /// (`stt/` + `tts/` + `vad/` subfolders alongside `manifest.json`),
  /// this is used in place of the unpacked-datapack location — the
  /// `.dat` unpack step is skipped entirely.
  final String? _modelOverridePath;

  /// Set by the last [resolveModelRoot] call: true when the root came
  /// from the [_modelOverridePath] short-circuit. Used by [loadManifest]
  /// / [verifyAll] to decide whether to synthesise a manifest and skip
  /// hash verification.
  bool _resolvedFromOverride = false;

  /// Resolves the on-disk root where the on-device speech models live.
  ///
  /// Resolution order:
  ///   1. Test `overrideRoot` (highest priority — keeps existing tests).
  ///   2. `app_config.json` `model` path, if set AND the directory has
  ///      a usable layout (see [_hasSherpaLayout]). Lets the admin
  ///      pre-place models on the sdcard and skip every `.dat` unpack
  ///      at runtime.
  ///   3. The unpacked-datapack location, read back from the install
  ///      state file via [unpackedRootForGroup] — the original flow.
  ///
  /// Before any of those resolve, a placeholder dir is returned so
  /// `snapshot()` reports `manifestMissing` and the router can send
  /// the user to the speech-setup screen.
  Future<Directory> resolveModelRoot() async {
    Directory root;
    _resolvedFromOverride = false;

    if (_overrideRoot != null) {
      root = Directory(p.join(_overrideRoot.path, 'models'));
    } else if (_modelOverridePath != null && _modelOverridePath.isNotEmpty) {
      final dir = Directory(_modelOverridePath);
      if (dir.existsSync() && _hasSherpaLayout(dir)) {
        debugPrint('[model-registry] using app_config.json model override '
            '→ ${dir.path}');
        _resolvedFromOverride = true;
        root = dir;
      } else {
        debugPrint(
            '[model-registry] model override path "$_modelOverridePath" '
            'missing or has no expected layout '
            '(needs stt/ with .onnx + tokens, plus tts/ and vad/) — '
            'falling back to unpacked .dat');
        root = await _resolveUnpackedRoot();
      }
    } else {
      root = await _resolveUnpackedRoot();
    }

    if (!root.existsSync()) {
      root.createSync(recursive: true);
    }
    return root;
  }

  Future<Directory> _resolveUnpackedRoot() async {
    final paths = await DataPackPaths.resolve();
    final subroot = await unpackedRootForGroup(paths, 'speech');
    return subroot != null
        ? Directory(subroot)
        : Directory(p.join(paths.unpackedRoot.path, '_speech_not_installed'));
  }

  /// True if [dir] looks like a usable sherpa-onnx model root — a
  /// `stt/` subdirectory containing at least one `.onnx` file and a
  /// `tokens*` file. We don't require a specific recogniser flavour
  /// here (transducer vs whisper); the STT service decides which one
  /// to build based on what's actually present.
  bool _hasSherpaLayout(Directory dir) {
    final sttDir = Directory(p.join(dir.path, 'stt'));
    if (!sttDir.existsSync()) return false;
    var hasOnnx = false;
    var hasTokens = false;
    for (final entity in sttDir.listSync(followLinks: false)) {
      if (entity is! File) continue;
      final name = p.basename(entity.path).toLowerCase();
      if (name.endsWith('.onnx')) hasOnnx = true;
      if (name.startsWith('tokens')) hasTokens = true;
      if (hasOnnx && hasTokens) return true;
    }
    return false;
  }

  Future<File> _manifestFile() async {
    final root = await resolveModelRoot();
    return File(p.join(root.path, 'manifest.json'));
  }

  Future<ModelManifest?> loadManifest() async {
    final file = await _manifestFile();
    if (file.existsSync()) {
      try {
        final raw = await file.readAsString();
        final j = jsonDecode(raw) as Map<String, dynamic>;
        return ModelManifest.fromJson(j);
      } catch (_) {
        return null;
      }
    }
    // No manifest on disk. When the root came from the app_config.json
    // override, admin probably placed raw files without a manifest —
    // build one by scanning the directory so the rest of the pipeline
    // (snapshot, STT _resolveListedFile) keeps working.
    if (_resolvedFromOverride) {
      final root = await resolveModelRoot();
      return _synthesizeManifest(root);
    }
    return null;
  }

  Future<ModelManifest> _synthesizeManifest(Directory root) async {
    final files = <ModelFile>[];
    await for (final entity
        in root.list(recursive: true, followLinks: false)) {
      if (entity is! File) continue;
      final rel = p.relative(entity.path, from: root.path);
      // Manifest convention is forward-slash relative paths.
      final relForward = rel.replaceAll(Platform.pathSeparator, '/');
      files.add(ModelFile(
        relativePath: relForward,
        sha256: '', // not verified — synthesized
        sizeBytes: await entity.length(),
      ));
    }
    debugPrint('[model-registry] synthesized manifest from ${root.path} '
        '(${files.length} file(s))');
    return ModelManifest(
      version: 'override',
      sttModel: 'override',
      ttsModel: 'override',
      vadModel: 'override',
      voices: const [],
      files: files,
      synthesized: true,
    );
  }

  /// SHA-256 every file listed in the manifest — except for synthesized
  /// manifests (admin override), where presence is the only check we
  /// have: there's no signed hash to verify against.
  Future<List<FileVerification>> verifyAll(ModelManifest manifest) async {
    final root = await resolveModelRoot();
    final results = <FileVerification>[];
    for (final f in manifest.files) {
      final path = p.join(root.path,
          f.relativePath.replaceAll('/', Platform.pathSeparator));
      final file = File(path);
      if (!file.existsSync()) {
        results.add(FileVerification(
          file: f,
          status: FileVerificationStatus.missing,
          message: 'Not found: $path',
        ));
        continue;
      }
      if (manifest.synthesized) {
        // Admin-placed files via the app_config.json `stt` override —
        // size & hash are unknown, presence is enough.
        results.add(FileVerification(
            file: f, status: FileVerificationStatus.ok));
        continue;
      }
      final stat = file.statSync();
      if (stat.size != f.sizeBytes) {
        results.add(FileVerification(
          file: f,
          status: FileVerificationStatus.sizeMismatch,
          message: 'Expected ${f.sizeBytes} bytes, got ${stat.size}',
        ));
        continue;
      }
      final bytes = await file.readAsBytes();
      final digest = sha256.convert(bytes).toString();
      if (digest != f.sha256) {
        results.add(FileVerification(
          file: f,
          status: FileVerificationStatus.hashMismatch,
          message: 'Hash mismatch',
        ));
        continue;
      }
      results.add(FileVerification(file: f, status: FileVerificationStatus.ok));
    }
    return results;
  }

  /// One-shot resolve → load manifest → verify → snapshot.
  Future<ModelRegistrySnapshot> snapshot() async {
    final root = await resolveModelRoot();
    final manifest = await loadManifest();
    if (manifest == null) {
      return ModelRegistrySnapshot(
        status: ModelRegistryStatus.manifestMissing,
        modelRoot: root.path,
      );
    }
    final verifications = await verifyAll(manifest);
    final allOk = verifications.every(
      (v) => v.status == FileVerificationStatus.ok,
    );
    return ModelRegistrySnapshot(
      status: allOk ? ModelRegistryStatus.ready : ModelRegistryStatus.corrupt,
      modelRoot: root.path,
      manifest: manifest,
      verifications: verifications,
    );
  }

  /// Resolves the absolute path to a file inside the model root.
  /// Used by sherpa-onnx services to point native code at the bundle.
  Future<String> resolveFile(String relativePath) async {
    final root = await resolveModelRoot();
    return p.join(root.path, relativePath);
  }
}

final modelRegistryProvider = Provider<ModelRegistry>((ref) {
  // Pull the optional `model` override path out of app_config.json so
  // the registry can short-circuit straight to admin-placed models.
  // `valueOrNull` is null until appConfigProvider resolves; at app
  // boot we await appConfigProvider before this is read.
  final cfg = ref.watch(appConfigProvider).valueOrNull;
  return ModelRegistry(modelOverridePath: cfg?.modelPath);
});

/// Snapshot used to gate UI (Models not installed screen, mic button visibility,
/// Settings → Storage tile).
final modelRegistrySnapshotProvider =
    FutureProvider<ModelRegistrySnapshot>((ref) async {
  return ref.read(modelRegistryProvider).snapshot();
});
